# Copyright BigchainDB GmbH and BigchainDB contributors
# SPDX-License-Identifier: (Apache-2.0 AND CC-BY-4.0)
# Code is Apache-2.0 and docs are CC-BY-4.0

---
- name: Removing apt cache lists
  file:
    path: /var/lib/apt/lists/*
    state: absent
    force: yes
  tags: [mongodb]

- name: Update Cache
  apt: update_cache=yes
  tags: [mongodb]

- name: Add APT Key | apt
  apt_key:
    keyserver: "{{ apt_keyserver }}"
    id: "{{ apt_key_fingerprint }}"
    state: present
  tags: [mongodb]

- name: Add MongoDB repo and update cache | apt
  apt_repository:
    repo: "{{ mongodb_apt_repo }}"
    state: present
    update_cache: no
  when: distribution_name == "ubuntu"
  tags: [mongodb]

- name: Add MongoDB repo and update cache | deb
  apt_repository:
    repo: "{{ mongodb_deb_repo }}"
    state: present
    update_cache: no
  when: distribution_name == "debian"
  tags: [mongodb]

- name: Install MongoDB | apt
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ mongodb_package }}"
  tags: [mongodb]
