# Copyright BigchainDB GmbH and BigchainDB contributors
# SPDX-License-Identifier: (Apache-2.0 AND CC-BY-4.0)
# Code is Apache-2.0 and docs are CC-BY-4.0

---
- name: Install dependencies py36 | yum
  yum:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - "yum-utils"
    - "https://centos7.iuscommunity.org/ius-release.rpm"
  tags: [py36]

- name: Install py36 | yum
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "python36u"
    - "python36u-pip"
    - "python36u-devel"
  tags: [py36]