# Copyright BigchainDB GmbH and BigchainDB contributors
# SPDX-License-Identifier: (Apache-2.0 AND CC-BY-4.0)
# Code is Apache-2.0 and docs are CC-BY-4.0

apiVersion: v1
kind: Service
metadata:
  name: bdb-instance-0
  namespace: default
  labels:
    name: bdb-instance-0
spec:
  selector:
    app: bdb-instance-0-ss
  ports:
  - port: 9984
    targetPort: 9984
    name: bdb-api-port
    protocol: TCP
  - port: 9985
    targetPort: 9985
    name: bdb-ws-port
    protocol: TCP
  - port: 26658
    targetPort: 26658
    name: tm-abci-port
    protocol: TCP
  - port: 26656
    targetPort: 26656
    name: tm-p2p-port
    protocol: TCP
  - port: 26657
    targetPort: 26657
    name: tm-rpc-port
    protocol: TCP
  - port: 9986
    targetPort: 9986
    name: pub-key-access
    protocol: TCP
  type: ClusterIP
  clusterIP: None
